spring.application.name=kadai01
spring.datasource.url=jdbc:mysql://localhost/kadai01
spring.datasource.username = root
spring.datasource.password = password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
mybatis.configuration.map-underscore-to-camel-case=true